name: Release

on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  pull-requests: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies with Yarn
        run: |
          yarn install
          yarn webpack --mode production

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
          configuration: ".github/workflows/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Tag Name
        id: tag_name
        run: echo "TAG_VERSION_NAME=v${{ env.VERSION_NAME }}" >> $GITHUB_ENV
      - name: Upload Apks
        id: upload_apk
        run: pip install requests markdown && python .github/workflows/upload.py
        env:
          CHANGELOG: ${{steps.github_release.outputs.changelog}}
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
          HOST_ENV_VAR: ${{ secrets.HOST_ENV_VAR }}
          USERNAME_ENV_VAR: ${{ secrets.USERNAME_ENV_VAR }}
          PASSWORD_ENV_VAR: ${{ secrets.PASSWORD_ENV_VAR }}
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            dist/category.js
            dist/rule.js
